name: Lobby
version: 1.0
main: org.mason.lobby.Main
depend: [Citizens, HolographicDisplays]
commands:
  playercount:
    description: Display the player count on each connected server.
    usage: /playercount
  arena:
    description: Arena command
  uhc:
    description: UHC command
  mnpc:
    description: NPC command
  listnpcs:
    description: List NPCs command
  deletenpc:
     description: Delete NPC command
  upcomingmatch:
    description: Displays upcoming matches.