name: Lobby
version: 1.0
main: org.mason.lobby.Main
depend: [Citizens, HolographicDisplays]
commands:
  arena:
    description: Arena server command.
  uhc:
    description: UHC server command.
  upcomingmatch:
    description: Displays upcoming matches.
  setspawn:
    description: Set the spawn location.
  matchhologram:
    description: Set the match hologram location.